language: java
#jdk:
#  - oraclejdk8
script:
  mvn --version;
  mvn -f ccd_appengine/pom.xml install;
deploy:
  provider: gae
  keyfile: ccd-hausaufgabe-aaa404686878.json
  project: ccd-hausaufgabe
  verbosity: debug
  config: ccd_appengine/src/main/webapp/WEB-INF/appengine-web.xml
  
